name: flutter_cupertino_settings
description: Flutter widget to create an iOS settings-table (static TableView).
version: 0.0.7
author: Matthias Rupp <matthias.rupp@posteo.de>
homepage: https://github.com/matthinc/flutter_cupertino_settings

dependencies:
  flutter:
    sdk: flutter

